<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SenseNetIndexTools.Native</RootNamespace>
    <AssemblyName>sensenet-create-index-native</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SenseNet.Storage" Version="7.8.2-alpha.5" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="SenseNet.ContentRepository" Version="7.8.2-alpha.5" />
    <PackageReference Include="SenseNet.Search.Lucene29" Version="7.5.1" />
    <PackageReference Include="SenseNet.Search.Lucene29.Local" Version="7.5.1" />
    <PackageReference Include="SenseNet.Search.Lucene29.Common" Version="7.5.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />

    <PackageReference Include="SenseNet.AI.Text.SemanticKernel" Version="0.0.3" />
    <PackageReference Include="SenseNet.AI.Vision.Azure" Version="0.0.1-beta1" />
    <PackageReference Include="SenseNet.ContentRepository.MsSql" Version="1.1.2-alpha.5" />
    <PackageReference Include="SenseNet.Messaging.RabbitMQ" Version="1.2.0" />
    <PackageReference Include="SenseNet.OData" Version="1.1.2-alpha.5" />
    <PackageReference Include="SenseNet.OpenApi" Version="1.1.2-alpha.5" />
    <PackageReference Include="SenseNet.Security.EFCSecurityStore" Version="3.2.0" />
    <PackageReference Include="SenseNet.Security.Messaging.RabbitMQ" Version="1.3.1" />
    <PackageReference Include="SenseNet.Services.Core" Version="1.1.2-alpha.5" />
    <PackageReference Include="SenseNet.Services.Core.Install" Version="1.1.2-alpha.5" />
    <PackageReference Include="SenseNet.Services.Wopi" Version="1.0.2-alpha.5" />
    <PackageReference Include="SenseNet.WebHooks" Version="1.1.2-alpha.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SenseNetIndexTools.Core\SenseNetIndexTools.Core.csproj" />
  </ItemGroup>

</Project>
